name: Node.js Package Beta (23.x)

on: 
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true

# on:
#   push:
#     branches:
#       - "work-for-release-0.23.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm version minor
    - run: npm install
    - run: npm publish --tag 23x
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
